#!/bin/bash

if [ -f /etc/init.d/suse_studio_firstboot ];
then

  # Put commands to be run on the first boot of your appliance here
  echo "Running SUSE Studio first boot script..."

# detecting sensors for lm_sensors
yes | sudo sensors-detect

fi
